version: '3.7'

services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - RPC_URL:"wss://mainnet.infura.io/ws/v3/b6744db53a18407799db22924e0725db=value"
    